name: image
version: 4.0.17
description: >-
  Dart Image Library provides server and web apps the ability to load, manipulate,
  and save images with various image file formats.
homepage: https://github.com/brendan-duncan/image
documentation: https://github.com/brendan-duncan/image/blob/main/doc/README.md

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  archive: ^3.3.9
  meta: ^1.9.1
  xml: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.2
  build_test: ^2.2.0
  build_web_compilers: ^4.0.5
  http: ^1.1.0
  lints: ^2.0.1
  test: ^1.16.0
